/* tslint:disable */
/* eslint-disable */
/**
 * Crypto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiBalanceGet200ResponseData
 */
export interface ApiBalanceGet200ResponseData {
    /**
     * Актуальный баланс
     * @type {number}
     * @memberof ApiBalanceGet200ResponseData
     */
    balance: number;
}

/**
 * Check if a given object implements the ApiBalanceGet200ResponseData interface.
 */
export function instanceOfApiBalanceGet200ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "balance" in value;

    return isInstance;
}

export function ApiBalanceGet200ResponseDataFromJSON(json: any): ApiBalanceGet200ResponseData {
    return ApiBalanceGet200ResponseDataFromJSONTyped(json, false);
}

export function ApiBalanceGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiBalanceGet200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': json['balance'],
    };
}

export function ApiBalanceGet200ResponseDataToJSON(value?: ApiBalanceGet200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': value.balance,
    };
}

