/* tslint:disable */
/* eslint-disable */
/**
 * Crypto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiBalanceGet200ResponseData } from './ApiBalanceGet200ResponseData';
import {
    ApiBalanceGet200ResponseDataFromJSON,
    ApiBalanceGet200ResponseDataFromJSONTyped,
    ApiBalanceGet200ResponseDataToJSON,
} from './ApiBalanceGet200ResponseData';

/**
 * 
 * @export
 * @interface ApiBalanceGet200Response
 */
export interface ApiBalanceGet200Response {
    /**
     * 
     * @type {ApiBalanceGet200ResponseData}
     * @memberof ApiBalanceGet200Response
     */
    data: ApiBalanceGet200ResponseData;
}

/**
 * Check if a given object implements the ApiBalanceGet200Response interface.
 */
export function instanceOfApiBalanceGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ApiBalanceGet200ResponseFromJSON(json: any): ApiBalanceGet200Response {
    return ApiBalanceGet200ResponseFromJSONTyped(json, false);
}

export function ApiBalanceGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiBalanceGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ApiBalanceGet200ResponseDataFromJSON(json['data']),
    };
}

export function ApiBalanceGet200ResponseToJSON(value?: ApiBalanceGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ApiBalanceGet200ResponseDataToJSON(value.data),
    };
}

