/* tslint:disable */
/* eslint-disable */
/**
 * Crypto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiCoinsGet200ResponseDataInner } from './ApiCoinsGet200ResponseDataInner';
import {
    ApiCoinsGet200ResponseDataInnerFromJSON,
    ApiCoinsGet200ResponseDataInnerFromJSONTyped,
    ApiCoinsGet200ResponseDataInnerToJSON,
} from './ApiCoinsGet200ResponseDataInner';
import type { ApiCoinsGet200ResponseMeta } from './ApiCoinsGet200ResponseMeta';
import {
    ApiCoinsGet200ResponseMetaFromJSON,
    ApiCoinsGet200ResponseMetaFromJSONTyped,
    ApiCoinsGet200ResponseMetaToJSON,
} from './ApiCoinsGet200ResponseMeta';

/**
 * 
 * @export
 * @interface ApiCoinsGet200Response
 */
export interface ApiCoinsGet200Response {
    /**
     * 
     * @type {Array<ApiCoinsGet200ResponseDataInner>}
     * @memberof ApiCoinsGet200Response
     */
    data: Array<ApiCoinsGet200ResponseDataInner>;
    /**
     * 
     * @type {ApiCoinsGet200ResponseMeta}
     * @memberof ApiCoinsGet200Response
     */
    meta: ApiCoinsGet200ResponseMeta;
}

/**
 * Check if a given object implements the ApiCoinsGet200Response interface.
 */
export function instanceOfApiCoinsGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;

    return isInstance;
}

export function ApiCoinsGet200ResponseFromJSON(json: any): ApiCoinsGet200Response {
    return ApiCoinsGet200ResponseFromJSONTyped(json, false);
}

export function ApiCoinsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCoinsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ApiCoinsGet200ResponseDataInnerFromJSON)),
        'meta': ApiCoinsGet200ResponseMetaFromJSON(json['meta']),
    };
}

export function ApiCoinsGet200ResponseToJSON(value?: ApiCoinsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ApiCoinsGet200ResponseDataInnerToJSON)),
        'meta': ApiCoinsGet200ResponseMetaToJSON(value.meta),
    };
}

