/* tslint:disable */
/* eslint-disable */
/**
 * Crypto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiCoinsIdTransferPostRequest
 */
export interface ApiCoinsIdTransferPostRequest {
    /**
     * Сумма трансфера в центах
     * @type {number}
     * @memberof ApiCoinsIdTransferPostRequest
     */
    amount?: number;
}

/**
 * Check if a given object implements the ApiCoinsIdTransferPostRequest interface.
 */
export function instanceOfApiCoinsIdTransferPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiCoinsIdTransferPostRequestFromJSON(json: any): ApiCoinsIdTransferPostRequest {
    return ApiCoinsIdTransferPostRequestFromJSONTyped(json, false);
}

export function ApiCoinsIdTransferPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCoinsIdTransferPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
    };
}

export function ApiCoinsIdTransferPostRequestToJSON(value?: ApiCoinsIdTransferPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
    };
}

