/* tslint:disable */
/* eslint-disable */
/**
 * Crypto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiBalanceGet200Response,
} from '../models';
import {
    ApiBalanceGet200ResponseFromJSON,
    ApiBalanceGet200ResponseToJSON,
} from '../models';

/**
 * 
 */
export class BalanceApi extends runtime.BaseAPI {

    /**
     * Баланс текущего пользователя
     */
    async apiBalanceGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiBalanceGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/balance`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiBalanceGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Баланс текущего пользователя
     */
    async apiBalanceGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiBalanceGet200Response> {
        const response = await this.apiBalanceGetRaw(initOverrides);
        return await response.value();
    }

}
